# Generated by Django 3.1.3 on 2008-12-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner_id',
            new_name='user_id',
        ),
    ]
