# Generated by Django 3.1.1 on 2020-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20090101_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
